/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cmepps_final.ventanas;

import javax.swing.WindowConstants;

/**
 *
 * @author anaor
 */
public class VentanaISBGS extends javax.swing.JFrame {
    double PF; 
    String PFNA_txt, FA_txt;
    double CE, EE, CD, ED;
    String CE_txt, EE_txt, CD_txt, ED_txt;
    
    /**
     * Creates new form VentanaISBGS
     */
    public VentanaISBGS() {
        initComponents();
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Esfuerzo_texto = new javax.swing.JLabel();
        label_PF_Esf = new javax.swing.JLabel();
        label_EE = new javax.swing.JLabel();
        Igual = new javax.swing.JLabel();
        label_resultado_Esfuerzo = new javax.swing.JLabel();
        Duracion_texto = new javax.swing.JLabel();
        label_PF_Dur = new javax.swing.JLabel();
        Igual1 = new javax.swing.JLabel();
        label_resultado_Duracion = new javax.swing.JLabel();
        Mensaje = new javax.swing.JLabel();
        PFNA_texto = new javax.swing.JLabel();
        FA_texto = new javax.swing.JLabel();
        label_PFNA_introducir = new javax.swing.JTextField();
        label_FA_introducir = new javax.swing.JTextField();
        label_Calcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelComboBox_esf = new javax.swing.JComboBox<>();
        labelComboBox_dur = new javax.swing.JComboBox<>();
        label_CD = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_CE = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_ED = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Esfuerzo_texto.setText("Esfuerzo =");

        label_PF_Esf.setText("00");

        label_EE.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        label_EE.setText("E");

        Igual.setText("=");

        label_resultado_Esfuerzo.setText("00'00");

        Duracion_texto.setText("Duración =");

        label_PF_Dur.setText("00");

        Igual1.setText("=");

        label_resultado_Duracion.setText("00'00");

        Mensaje.setText("Por favor, introduzca los siguientes datos: ");

        PFNA_texto.setText("PFNA:");

        FA_texto.setText("FA:");

        label_PFNA_introducir.setText("        ");
        label_PFNA_introducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_PFNA_introducirActionPerformed(evt);
            }
        });

        label_FA_introducir.setText("        ");
        label_FA_introducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_FA_introducirActionPerformed(evt);
            }
        });

        label_Calcular.setText("Calcular");
        label_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_CalcularActionPerformed(evt);
            }
        });

        jLabel1.setText("horas");

        jLabel2.setText("horas");

        labelComboBox_esf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MF", "MR", "PC", "Multi", "3GL", "4GL", "GenAp", "Mantenimiento", "Nuevo", "MF-3GL", "MF-4GL", "MF-GenAp", "MR-3GL", "MR-4GL", "PC-3GL", "PC-4GL", "Multi-3GL", "Multi-4GL", "MF-3GL-Mantenimineto" }));
        labelComboBox_esf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelComboBox_esfActionPerformed(evt);
            }
        });

        labelComboBox_dur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "Multi", "4GL", "Nuevo", "PC-4GL", "Multi-4GL", "PC-4GL-Nuevo", "Multi-4GL-Nuevo" }));
        labelComboBox_dur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelComboBox_durActionPerformed(evt);
            }
        });

        label_CD.setText("C");

        jLabel3.setText("x");

        label_CE.setText("C");

        jLabel4.setText("x");

        label_ED.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        label_ED.setText("E");

        jLabel5.setText("        ");

        jLabel6.setText("     ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Mensaje))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(PFNA_texto)
                        .addGap(10, 10, 10)
                        .addComponent(label_PFNA_introducir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(FA_texto)
                        .addGap(25, 25, 25)
                        .addComponent(label_FA_introducir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(label_ED, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(label_Calcular))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Esfuerzo_texto)
                                .addGap(13, 13, 13)
                                .addComponent(label_CE)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel3)
                                .addGap(14, 14, 14)
                                .addComponent(label_PF_Esf)
                                .addGap(6, 6, 6)
                                .addComponent(label_EE)
                                .addGap(14, 14, 14)
                                .addComponent(Igual)
                                .addGap(11, 11, 11)
                                .addComponent(label_resultado_Esfuerzo)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(labelComboBox_esf, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Duracion_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label_CD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(label_PF_Dur)
                                .addGap(26, 26, 26)
                                .addComponent(Igual1)
                                .addGap(11, 11, 11)
                                .addComponent(label_resultado_Duracion)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(labelComboBox_dur, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Mensaje)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(PFNA_texto))
                    .addComponent(label_PFNA_introducir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(FA_texto))
                            .addComponent(label_FA_introducir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Esfuerzo_texto))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(label_CE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(label_PF_Esf))
                            .addComponent(label_EE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Igual))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(label_resultado_Esfuerzo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(labelComboBox_esf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(label_ED, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Duracion_texto)
                    .addComponent(jLabel4)
                    .addComponent(label_CD)
                    .addComponent(label_PF_Dur)
                    .addComponent(Igual1)
                    .addComponent(label_resultado_Duracion)
                    .addComponent(jLabel2)
                    .addComponent(labelComboBox_dur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label_Calcular)
                .addGap(35, 35, 35)
                .addComponent(jLabel6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_PFNA_introducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_PFNA_introducirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_label_PFNA_introducirActionPerformed

    private void label_FA_introducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_FA_introducirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_FA_introducirActionPerformed
 
    private void calculoPF(){
        //PF = PFNA * FA
        //PFNA y FA los extraigo de Ventana PFA
                
        //de string a int
        PFNA_txt = label_PFNA_introducir.getText();
        int PFNA_num = Integer.parseInt(PFNA_txt);
        
        FA_txt = label_FA_introducir.getText();
        int FA_num = Integer.parseInt(FA_txt);
                        
        PF = PFNA_num * FA_num; 
        
        //de int a string
        String PF_texto = PF+"";      
        
        label_PF_Esf.setText(PF_texto);   
        label_PF_Dur.setText(PF_texto);
    }
    
     private void actualizarTipoEsfuerzo(){
        String tipo = (String) labelComboBox_esf.getSelectedItem();
        switch (tipo) {
            case "MF":
                CE=49.02;
                EE=0.736;
                break;
            case "MR":
                CE=78.88;
                EE=0.646;
                break;
            case "PC":
                CE=48.90;
                EE=0.661;
                break;
            case "Multi":
                CE=16.01;
                EE=0.865;
                break;
            case "3GL":
                CE=54.65;
                EE=0.717;
                break;
            case "4GL":
                CE=29.50;
                EE=0.758;
                break;
            case "GenAp": 
                CE=68.11;
                EE=0.660;
                break;
            case "Mantenimiento":
                CE=52.58;
                EE=0.683;
                break;
            case "Nuevo":
                CE=39.05;
                EE=0.731;
                break;
            case "MF-3GL":
                CE=65.37;
                EE=0.705;
                break;
            case "MF-4GL":
                CE=52.09;
                EE=0.640;
                break;
            case "MF-GenAp":
                CE=65.68;
                EE=0.692;
                break;
            case "MR-3GL":
                CE=126.3;
                EE=0.565;
                break;
            case "MR-4GL":
                CE=62.35;
                EE=0.694;
                break;
            case "PC-3GL":
                CE=60.46;
                EE=0.648;
                break;
            case "PC-4GL":
                CE=36.48;
                EE=0.694;
                break;
            case "Multi-3GL":   
                CE=19.82;
                EE=0.666;
                break;
            case "Multi-4GL":
                CE=6.49;
                EE=0.983;
                break;
            case "MF-3GL-Mantenimiento":  
                CE=83.27;
                EE=0.650;
                break;                
        }
    
        CE_txt = CE+"";
        EE_txt = EE+"";
        label_CE.setText(CE_txt);
        label_EE.setText(EE_txt);
    }
    
    
    private void actualizarTipoDuracion(){
        String tipo = (String) labelComboBox_dur.getSelectedItem();
        switch (tipo) {
            case "PC":
                CD=0.503;
                ED=0.409;
                break;
            case "Multi":
                CD=0.679;
                ED=0.341;
                break;
            case "4GL":
                CD=0.578;
                ED=0.393;
                break;
            case "Nuevo":
                CD=0.739;
                ED=0.359;
                break;
            case "PC-4GL":
                CD=0.348;
                ED=0.471;
                break;
            case "Multi-4GL":
                CD=0.366;
                ED=0.451;
                break;
            case "PC-4GL-Nuevo":  
                CD=0.250;
                ED=0.515;
                break;       
            case "Multi-4GL-Nuevo":  
                CD=0.240;
                ED=0.518;
                break;  
        }
    
        CD_txt = CD+"";
        ED_txt = ED+"";
        label_CD.setText(CD_txt);
        label_ED.setText(ED_txt);
    }
    
    private void label_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_CalcularActionPerformed
        // TODO add your handling code here:
        double esfuerzo, duracion, elev1, elev2;
        String esf_txt, dur_txt;
                
        calculoPF();
        
        //esfuerzo = C * PF^E
        elev1 = Math.pow(PF, EE);
        esfuerzo = CE * elev1;
                
        //duracion = C * PF^E
        elev2 = Math.pow(PF, ED);
        duracion = CD * elev2;
        
        //las convierto a texto
        esf_txt = esfuerzo+"";
        dur_txt = duracion+"";
        
        label_resultado_Esfuerzo.setText(esf_txt);
        label_resultado_Duracion.setText(dur_txt);        
    }//GEN-LAST:event_label_CalcularActionPerformed

    private void labelComboBox_esfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelComboBox_esfActionPerformed
        // TODO add your handling code here:
        actualizarTipoEsfuerzo();
    }//GEN-LAST:event_labelComboBox_esfActionPerformed

    private void labelComboBox_durActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelComboBox_durActionPerformed
        // TODO add your handling code here:
        actualizarTipoDuracion();
    }//GEN-LAST:event_labelComboBox_durActionPerformed
 
      
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaISBGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaISBGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaISBGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaISBGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaISBGS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Duracion_texto;
    private javax.swing.JLabel Esfuerzo_texto;
    private javax.swing.JLabel FA_texto;
    private javax.swing.JLabel Igual;
    private javax.swing.JLabel Igual1;
    private javax.swing.JLabel Mensaje;
    private javax.swing.JLabel PFNA_texto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> labelComboBox_dur;
    private javax.swing.JComboBox<String> labelComboBox_esf;
    private javax.swing.JLabel label_CD;
    private javax.swing.JLabel label_CE;
    private javax.swing.JButton label_Calcular;
    private javax.swing.JLabel label_ED;
    private javax.swing.JLabel label_EE;
    private javax.swing.JTextField label_FA_introducir;
    private javax.swing.JTextField label_PFNA_introducir;
    private javax.swing.JLabel label_PF_Dur;
    private javax.swing.JLabel label_PF_Esf;
    private javax.swing.JLabel label_resultado_Duracion;
    private javax.swing.JLabel label_resultado_Esfuerzo;
    // End of variables declaration//GEN-END:variables
}
