/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cmepps_final.ventanas;

import cmepps_final.variabs.Elemento;
import static cmepps_final.ventanas.VentanaPFNA.elementos;
import java.util.ArrayList;
import javax.swing.WindowConstants;

/**
 *
 * @author Pablo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    static ArrayList<Elemento> elementos = new ArrayList<Elemento>();
    static int PFNA = 0;
    static int totalCar = 0;
    static double FA = 0;
    static int[] influencias = {0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    
    public int calcularPFNA()
    {
        int totalEE  = nTipoComplejidadPFNA("EE", "SIMPLE")*3 + nTipoComplejidadPFNA("EE", "MEDIA")*4 + nTipoComplejidadPFNA("EE", "COMPLEJA")*6;
        int totalSE  = nTipoComplejidadPFNA("SE", "SIMPLE")*4 + nTipoComplejidadPFNA("SE", "MEDIA")*5 + nTipoComplejidadPFNA("SE", "COMPLEJA")*7;
        int totalCE  = nTipoComplejidadPFNA("CE", "SIMPLE")*7 + nTipoComplejidadPFNA("CE", "MEDIA")*10 + nTipoComplejidadPFNA("CE", "COMPLEJA")*15;
        int totalFLI  = nTipoComplejidadPFNA("FLI", "SIMPLE")*5 + nTipoComplejidadPFNA("FLI", "MEDIA")*7 + nTipoComplejidadPFNA("FLI", "COMPLEJA")*10;
        int totalFLE  = nTipoComplejidadPFNA("FLE", "SIMPLE")*3 + nTipoComplejidadPFNA("FLE", "MEDIA")*4 + nTipoComplejidadPFNA("FLE", "COMPLEJA")*6;
        PFNA = totalCE+totalEE+totalFLE+totalFLI+totalSE;
        return PFNA;
    }
    

    public int nTipoComplejidadPFNA(String tipo, String complejidad)
    {
        int n = 0;
        for (int i = 0; i < elementos.size(); i++) {
            if (elementos.get(i).getTipo() == tipo && elementos.get(i).getComplejidad() == complejidad)
            {
                n++;
            }
        }
        return n;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuElementos = new javax.swing.JMenu();
        itemListado = new javax.swing.JMenuItem();
        itemPFNA = new javax.swing.JMenuItem();
        itemCaracteristicas = new javax.swing.JMenuItem();
        itemPFA = new javax.swing.JMenuItem();
        VentanaISBGS = new javax.swing.JMenuItem();

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Ana Orta Borrero");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ana Orta Borrero");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("PRÁCTICA FINAL CMEPPS");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Pablo González Díaz");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText(" 2021-2022");

        menuElementos.setText("Menú");
        menuElementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuElementosActionPerformed(evt);
            }
        });

        itemListado.setText("Menú elementos");
        itemListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListadoActionPerformed(evt);
            }
        });
        menuElementos.add(itemListado);

        itemPFNA.setText("Cálculo PFNA");
        itemPFNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPFNAActionPerformed(evt);
            }
        });
        menuElementos.add(itemPFNA);

        itemCaracteristicas.setText("Características generales");
        itemCaracteristicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCaracteristicasActionPerformed(evt);
            }
        });
        menuElementos.add(itemCaracteristicas);

        itemPFA.setText("Cálculo PFA");
        itemPFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPFAActionPerformed(evt);
            }
        });
        menuElementos.add(itemPFA);

        VentanaISBGS.setText("ISBGS");
        VentanaISBGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaISBGSActionPerformed(evt);
            }
        });
        menuElementos.add(VentanaISBGS);

        jMenuBar1.add(menuElementos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel5)))
                        .addGap(102, 102, 102))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuElementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuElementosActionPerformed
        // TODO add your handling code here:
        VentanaElementos ve = new VentanaElementos(elementos);
        ve.setVisible(true);
        ve.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuElementosActionPerformed

    private void itemListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListadoActionPerformed
        // TODO add your handling code here:
        VentanaElementos ve = new VentanaElementos(elementos);
        ve.setVisible(true);
        ve.setLocationRelativeTo(null);
    }//GEN-LAST:event_itemListadoActionPerformed

    private void itemPFNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPFNAActionPerformed
        // TODO add your handling code here:
        VentanaPFNA vpfna = new VentanaPFNA(elementos, PFNA);
        vpfna.setVisible(true);
        vpfna.setLocationRelativeTo(null);
    }//GEN-LAST:event_itemPFNAActionPerformed

    private void itemCaracteristicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCaracteristicasActionPerformed
        // TODO add your handling code here:
        VentanaCaracteristicasGenerales vce = new VentanaCaracteristicasGenerales(totalCar);
        vce.setVisible(true);
        vce.setLocationRelativeTo(null);
    }//GEN-LAST:event_itemCaracteristicasActionPerformed

    private void itemPFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPFAActionPerformed
        // TODO add your handling code here:
        VentanaPFA vpfa= new VentanaPFA(calcularPFNA(), totalCar);
        vpfa.setVisible(true);
        vpfa.setLocationRelativeTo(null);
    }//GEN-LAST:event_itemPFAActionPerformed

    private void VentanaISBGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaISBGSActionPerformed
        // TODO add your handling code here:
        VentanaISBGS vi= new VentanaISBGS(calcularPFNA());
        vi.setVisible(true);
        vi.setLocationRelativeTo(null);
    }//GEN-LAST:event_VentanaISBGSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem VentanaISBGS;
    private javax.swing.JMenuItem itemCaracteristicas;
    private javax.swing.JMenuItem itemListado;
    private javax.swing.JMenuItem itemPFA;
    private javax.swing.JMenuItem itemPFNA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuElementos;
    // End of variables declaration//GEN-END:variables
}
