/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cmepps_final.ventanas;

import javax.swing.WindowConstants;

/**
 *
 * @author anaor
 */
public class VentanaISBGS extends javax.swing.JFrame {
    double PF; 
    String PFNA_txt, FA_txt;
    static int PFNA;
    double CE, EE, CD, ED;
    String CE_txt, EE_txt, CD_txt, ED_txt;
    
    /**
     * Creates new form VentanaISBGS
     */
    public VentanaISBGS(int PFNA) {
        initComponents();
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.PFNA = PFNA;
        labelPFNA.setText(PFNA+"");
        labelFA.setText(0.65 + (VentanaPrincipal.totalCar *0.01)+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Esfuerzo_texto = new javax.swing.JLabel();
        label_PF_Esf = new javax.swing.JLabel();
        label_EE = new javax.swing.JLabel();
        Igual = new javax.swing.JLabel();
        label_resultado_Esfuerzo = new javax.swing.JLabel();
        Duracion_texto = new javax.swing.JLabel();
        label_PF_Dur = new javax.swing.JLabel();
        Igual1 = new javax.swing.JLabel();
        label_resultado_Duracion = new javax.swing.JLabel();
        PFNA_texto = new javax.swing.JLabel();
        FA_texto = new javax.swing.JLabel();
        label_Calcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelComboBox_esf = new javax.swing.JComboBox<>();
        labelComboBox_dur = new javax.swing.JComboBox<>();
        label_CD = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_CE = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label_ED = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelPFNA = new javax.swing.JLabel();
        labelFA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        Esfuerzo_texto.setText("Esfuerzo =");
        getContentPane().add(Esfuerzo_texto);
        Esfuerzo_texto.setBounds(50, 160, 80, 14);

        label_PF_Esf.setText("00");
        getContentPane().add(label_PF_Esf);
        label_PF_Esf.setBounds(170, 160, 30, 14);

        label_EE.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        label_EE.setText("E");
        getContentPane().add(label_EE);
        label_EE.setBounds(210, 150, 50, 13);

        Igual.setText("=");
        getContentPane().add(Igual);
        Igual.setBounds(250, 160, 8, 14);

        label_resultado_Esfuerzo.setText("00'00");
        getContentPane().add(label_resultado_Esfuerzo);
        label_resultado_Esfuerzo.setBounds(270, 160, 50, 14);

        Duracion_texto.setText("Duración =");
        getContentPane().add(Duracion_texto);
        Duracion_texto.setBounds(50, 200, 90, 14);

        label_PF_Dur.setText("00");
        getContentPane().add(label_PF_Dur);
        label_PF_Dur.setBounds(170, 200, 30, 14);

        Igual1.setText("=");
        getContentPane().add(Igual1);
        Igual1.setBounds(250, 200, 8, 14);

        label_resultado_Duracion.setText("00'00");
        getContentPane().add(label_resultado_Duracion);
        label_resultado_Duracion.setBounds(270, 200, 50, 14);

        PFNA_texto.setText("PFNA:");
        getContentPane().add(PFNA_texto);
        PFNA_texto.setBounds(50, 80, 50, 14);

        FA_texto.setText("FA:");
        getContentPane().add(FA_texto);
        FA_texto.setBounds(50, 100, 30, 20);

        label_Calcular.setText("Calcular");
        label_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_CalcularActionPerformed(evt);
            }
        });
        getContentPane().add(label_Calcular);
        label_Calcular.setBounds(160, 250, 110, 23);

        jLabel1.setText("horas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 160, 27, 14);

        jLabel2.setText("horas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 200, 40, 14);

        labelComboBox_esf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MF", "MR", "PC", "Multi", "3GL", "4GL", "GenAp", "Mantenimiento", "Nuevo", "MF-3GL", "MF-4GL", "MF-GenAp", "MR-3GL", "MR-4GL", "PC-3GL", "PC-4GL", "Multi-3GL", "Multi-4GL", "MF-3GL-Mantenimineto" }));
        labelComboBox_esf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelComboBox_esfActionPerformed(evt);
            }
        });
        getContentPane().add(labelComboBox_esf);
        labelComboBox_esf.setBounds(350, 160, 102, 20);

        labelComboBox_dur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "Multi", "4GL", "Nuevo", "PC-4GL", "Multi-4GL", "PC-4GL-Nuevo", "Multi-4GL-Nuevo" }));
        labelComboBox_dur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelComboBox_durActionPerformed(evt);
            }
        });
        getContentPane().add(labelComboBox_dur);
        labelComboBox_dur.setBounds(350, 200, 102, 20);

        label_CD.setText("C");
        getContentPane().add(label_CD);
        label_CD.setBounds(110, 200, 70, 14);

        jLabel3.setText("x");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 160, 6, 14);

        label_CE.setText("C");
        getContentPane().add(label_CE);
        label_CE.setBounds(110, 160, 70, 14);

        jLabel4.setText("x");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 200, 10, 14);

        label_ED.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        label_ED.setText("E");
        getContentPane().add(label_ED);
        label_ED.setBounds(210, 190, 60, 10);

        jLabel5.setText("        ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(351, 86, 24, 14);

        jLabel6.setText("     ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 310, 15, 14);

        labelPFNA.setText("0");
        getContentPane().add(labelPFNA);
        labelPFNA.setBounds(100, 80, 49, 14);

        labelFA.setText("0");
        getContentPane().add(labelFA);
        labelFA.setBounds(100, 100, 54, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void calculoPF(){
        //PF = PFNA * FA
        //PFNA y FA los extraigo de Ventana PFA
                
        //de string a int
        labelPFNA.setText(VentanaPrincipal.PFNA+"");
        double FA = 0.65 + (VentanaPrincipal.totalCar *0.01);
        labelFA.setText(FA+"");
                       
        PF = VentanaPrincipal.PFNA * FA; 
        PF = Math.round(PF * 100.0) / 100.0;
        //de int a string
        String PF_texto = PF+"";      
        
        label_PF_Esf.setText(PF_texto);   
        label_PF_Dur.setText(PF_texto);
        
        
    }
    
     private void actualizarTipoEsfuerzo(){
        String tipo = (String) labelComboBox_esf.getSelectedItem();
        switch (tipo) {
            case "MF":
                CE=49.02;
                EE=0.736;
                break;
            case "MR":
                CE=78.88;
                EE=0.646;
                break;
            case "PC":
                CE=48.90;
                EE=0.661;
                break;
            case "Multi":
                CE=16.01;
                EE=0.865;
                break;
            case "3GL":
                CE=54.65;
                EE=0.717;
                break;
            case "4GL":
                CE=29.50;
                EE=0.758;
                break;
            case "GenAp": 
                CE=68.11;
                EE=0.660;
                break;
            case "Mantenimiento":
                CE=52.58;
                EE=0.683;
                break;
            case "Nuevo":
                CE=39.05;
                EE=0.731;
                break;
            case "MF-3GL":
                CE=65.37;
                EE=0.705;
                break;
            case "MF-4GL":
                CE=52.09;
                EE=0.640;
                break;
            case "MF-GenAp":
                CE=65.68;
                EE=0.692;
                break;
            case "MR-3GL":
                CE=126.3;
                EE=0.565;
                break;
            case "MR-4GL":
                CE=62.35;
                EE=0.694;
                break;
            case "PC-3GL":
                CE=60.46;
                EE=0.648;
                break;
            case "PC-4GL":
                CE=36.48;
                EE=0.694;
                break;
            case "Multi-3GL":   
                CE=19.82;
                EE=0.666;
                break;
            case "Multi-4GL":
                CE=6.49;
                EE=0.983;
                break;
            case "MF-3GL-Mantenimiento":  
                CE=83.27;
                EE=0.650;
                break;                
        }
    
        CE_txt = CE+"";
        EE_txt = EE+"";
        label_CE.setText(CE_txt);
        label_EE.setText(EE_txt);
    }
    
    
    private void actualizarTipoDuracion(){
        String tipo = (String) labelComboBox_dur.getSelectedItem();
        switch (tipo) {
            case "PC":
                CD=0.503;
                ED=0.409;
                break;
            case "Multi":
                CD=0.679;
                ED=0.341;
                break;
            case "4GL":
                CD=0.578;
                ED=0.393;
                break;
            case "Nuevo":
                CD=0.739;
                ED=0.359;
                break;
            case "PC-4GL":
                CD=0.348;
                ED=0.471;
                break;
            case "Multi-4GL":
                CD=0.366;
                ED=0.451;
                break;
            case "PC-4GL-Nuevo":  
                CD=0.250;
                ED=0.515;
                break;       
            case "Multi-4GL-Nuevo":  
                CD=0.240;
                ED=0.518;
                break;  
        }
    
        CD_txt = CD+"";
        ED_txt = ED+"";
        label_CD.setText(CD_txt);
        label_ED.setText(ED_txt);
    }
    
    private void label_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_CalcularActionPerformed
        // TODO add your handling code here:
        double esfuerzo, duracion, elev1, elev2;
        String esf_txt, dur_txt;
                
        calculoPF();
        
        //esfuerzo = C * PF^E
        elev1 = Math.pow(PF, EE);
        esfuerzo = CE * elev1;
        esfuerzo = Math.round(esfuerzo * 100.0) / 100.0;   
        //duracion = C * PF^E
        elev2 = Math.pow(PF, ED);
        duracion = CD * elev2;
        duracion = Math.round(duracion * 100.0) / 100.0;   
        //las convierto a texto
        esf_txt = esfuerzo+"";
        dur_txt = duracion+"";
        
        label_resultado_Esfuerzo.setText(esf_txt);
        label_resultado_Duracion.setText(dur_txt);        
    }//GEN-LAST:event_label_CalcularActionPerformed

    private void labelComboBox_esfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelComboBox_esfActionPerformed
        // TODO add your handling code here:
        actualizarTipoEsfuerzo();
    }//GEN-LAST:event_labelComboBox_esfActionPerformed

    private void labelComboBox_durActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelComboBox_durActionPerformed
        // TODO add your handling code here:
        actualizarTipoDuracion();
    }//GEN-LAST:event_labelComboBox_durActionPerformed
 
      
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaISBGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaISBGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaISBGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaISBGS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaISBGS(PFNA).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Duracion_texto;
    private javax.swing.JLabel Esfuerzo_texto;
    private javax.swing.JLabel FA_texto;
    private javax.swing.JLabel Igual;
    private javax.swing.JLabel Igual1;
    private javax.swing.JLabel PFNA_texto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> labelComboBox_dur;
    private javax.swing.JComboBox<String> labelComboBox_esf;
    private javax.swing.JLabel labelFA;
    private javax.swing.JLabel labelPFNA;
    private javax.swing.JLabel label_CD;
    private javax.swing.JLabel label_CE;
    private javax.swing.JButton label_Calcular;
    private javax.swing.JLabel label_ED;
    private javax.swing.JLabel label_EE;
    private javax.swing.JLabel label_PF_Dur;
    private javax.swing.JLabel label_PF_Esf;
    private javax.swing.JLabel label_resultado_Duracion;
    private javax.swing.JLabel label_resultado_Esfuerzo;
    // End of variables declaration//GEN-END:variables
}
