/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cmepps_final.ventanas;

import cmepps_final.variabs.Elemento;
import java.util.ArrayList;
import javax.swing.WindowConstants;

/**
 *
 * @author Pablo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    static ArrayList<Elemento> elementos = new ArrayList<Elemento>();
    public VentanaPrincipal(ArrayList<Elemento> elementos) {
        initComponents();
        this.elementos = elementos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuElementos = new javax.swing.JMenu();
        itemListado = new javax.swing.JMenuItem();
        itemPFNA = new javax.swing.JMenuItem();
        itemCaracteristicas = new javax.swing.JMenuItem();
        itemPFA = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuElementos.setText("Menú");
        menuElementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuElementosActionPerformed(evt);
            }
        });

        itemListado.setText("Menú elementos");
        itemListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListadoActionPerformed(evt);
            }
        });
        menuElementos.add(itemListado);

        itemPFNA.setText("Cálculo PFNA");
        itemPFNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPFNAActionPerformed(evt);
            }
        });
        menuElementos.add(itemPFNA);

        itemCaracteristicas.setText("Características generales");
        itemCaracteristicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCaracteristicasActionPerformed(evt);
            }
        });
        menuElementos.add(itemCaracteristicas);

        itemPFA.setText("Cálculo PFA");
        menuElementos.add(itemPFA);

        jMenuBar1.add(menuElementos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuElementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuElementosActionPerformed
        // TODO add your handling code here:
        VentanaElementos ve = new VentanaElementos(elementos);
        ve.setVisible(true);
        ve.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuElementosActionPerformed

    private void itemListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListadoActionPerformed
        // TODO add your handling code here:
        VentanaElementos ve = new VentanaElementos(elementos);
        ve.setVisible(true);
        ve.setLocationRelativeTo(null);
    }//GEN-LAST:event_itemListadoActionPerformed

    private void itemPFNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPFNAActionPerformed
        // TODO add your handling code here:
        VentanaPFNA vpfna = new VentanaPFNA(elementos);
        vpfna.setVisible(true);
        vpfna.setLocationRelativeTo(null);
    }//GEN-LAST:event_itemPFNAActionPerformed

    private void itemCaracteristicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCaracteristicasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCaracteristicasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal(elementos).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCaracteristicas;
    private javax.swing.JMenuItem itemListado;
    private javax.swing.JMenuItem itemPFA;
    private javax.swing.JMenuItem itemPFNA;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuElementos;
    // End of variables declaration//GEN-END:variables
}
